auth:
  jwt:
    secret: "very secret key"
    issuer: "auth-service"
    accessTokenTTL: 5s
    refreshTokenTTL: 1h
  noAuthRoutes:
    - POST /v1/auth/register
    - POST /v1/auth/login
    - POST /v1/auth/refresh

http:
  port: 8080
  shutdownTimeout: 3s

db:
  requestTimeout: 3s
  postgres:
    conn: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?pool_max_conns=10&sslmode=${POSTGRES_SSL_MODE}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logger:
  level: info
  disableCaller: false
  disableStacktrace: true
  enableDateTime: true