// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: template.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Template_CreateProductV1_FullMethodName = "/template.Template/CreateProductV1"
	Template_GetProductV1_FullMethodName    = "/template.Template/GetProductV1"
)

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateClient interface {
	CreateProductV1(ctx context.Context, in *CreateProductV1Request, opts ...grpc.CallOption) (*CreateProductV1Response, error)
	GetProductV1(ctx context.Context, in *GetProductV1Request, opts ...grpc.CallOption) (*GetProductV1Response, error)
}

type templateClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateClient(cc grpc.ClientConnInterface) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) CreateProductV1(ctx context.Context, in *CreateProductV1Request, opts ...grpc.CallOption) (*CreateProductV1Response, error) {
	out := new(CreateProductV1Response)
	err := c.cc.Invoke(ctx, Template_CreateProductV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) GetProductV1(ctx context.Context, in *GetProductV1Request, opts ...grpc.CallOption) (*GetProductV1Response, error) {
	out := new(GetProductV1Response)
	err := c.cc.Invoke(ctx, Template_GetProductV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
// All implementations should embed UnimplementedTemplateServer
// for forward compatibility
type TemplateServer interface {
	CreateProductV1(context.Context, *CreateProductV1Request) (*CreateProductV1Response, error)
	GetProductV1(context.Context, *GetProductV1Request) (*GetProductV1Response, error)
}

// UnimplementedTemplateServer should be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (UnimplementedTemplateServer) CreateProductV1(context.Context, *CreateProductV1Request) (*CreateProductV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductV1 not implemented")
}
func (UnimplementedTemplateServer) GetProductV1(context.Context, *GetProductV1Request) (*GetProductV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductV1 not implemented")
}

// UnsafeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServer will
// result in compilation errors.
type UnsafeTemplateServer interface {
	mustEmbedUnimplementedTemplateServer()
}

func RegisterTemplateServer(s grpc.ServiceRegistrar, srv TemplateServer) {
	s.RegisterService(&Template_ServiceDesc, srv)
}

func _Template_CreateProductV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).CreateProductV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_CreateProductV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).CreateProductV1(ctx, req.(*CreateProductV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_GetProductV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).GetProductV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_GetProductV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).GetProductV1(ctx, req.(*GetProductV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Template_ServiceDesc is the grpc.ServiceDesc for Template service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Template_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "template.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductV1",
			Handler:    _Template_CreateProductV1_Handler,
		},
		{
			MethodName: "GetProductV1",
			Handler:    _Template_GetProductV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}
