// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PasswordUpdater is an autogenerated mock type for the PasswordUpdater type
type PasswordUpdater struct {
	mock.Mock
}

// UpdatePassword provides a mock function with given fields: ctx, userID, hashedPassword
func (_m *PasswordUpdater) UpdatePassword(ctx context.Context, userID string, hashedPassword string) error {
	ret := _m.Called(ctx, userID, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPasswordUpdater creates a new instance of PasswordUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordUpdater {
	mock := &PasswordUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
