// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/riabininkf/http-auth-example/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserByIdProvider is an autogenerated mock type for the UserByIdProvider type
type UserByIdProvider struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *UserByIdProvider) GetByID(ctx context.Context, userID string) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserByIdProvider creates a new instance of UserByIdProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserByIdProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserByIdProvider {
	mock := &UserByIdProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
