// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/riabininkf/http-auth-example/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserRegistrar is an autogenerated mock type for the UserRegistrar type
type UserRegistrar struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, user
func (_m *UserRegistrar) Save(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRegistrar creates a new instance of UserRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegistrar {
	mock := &UserRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
